ref:
  GRCh37_ensembl:
    species: homo_sapiens
    build: GRCh37
    release: 106
    gtf: 87 # gtf release differs from release

  GRCh38_ensembl:
    species: homo_sapiens
    build: GRCh38
    release: 106

  T2T_CHM13:
    species: homo_sapiens
    build: T2T_CHM13_v2-0
    release: 110
    genome:
      fasta_url: https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/latest_assembly_versions/GCF_009914755.1_T2T-CHM13v2.0/GCF_009914755.1_T2T-CHM13v2.0_genomic.fna.gz
    annotation:
      gtf_url: https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Homo_sapiens/latest_assembly_versions/GCF_009914755.1_T2T-CHM13v2.0/GCF_009914755.1_T2T-CHM13v2.0_genomic.gtf.gz

